spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bezkoder_db2
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com

springdoc:
  api-docs:
#    enabled: false
    path: /bezkoder-api-docs
  swagger-ui:
#    enabled: false
    path: /bezkoder-documentation
    tryItOutEnabled: true
    filter: true
    # operationsSorter: method
    # tagsSorter: alpha
  # packages-to-scan: com.bezkoder.spring.swagger.controller
