spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bezkoder_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect